name: 'Table Actions'
description: 'Updates GitHub project tables based on issues'
inputs:
  sync-with-table:
    description: 'A JSON array of objects containing label and tableNumber'
    required: false
  sync-fields:
    description: 'A JSON array of objects containing label, issueField, tableNumber, and tableField'
    required: false
  ghToken:
    description: 'A GitHub token with write access to the destination project and read access to the source issue. See https://docs.github.com/en/actions/reference/encrypted-secrets'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
